name: SonarQube Scan
 
on:
  push:
    branches:
      - main  # adjust branch name as needed
 
jobs:
  sonarqube:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: sonarqube-${{ runner.os }}-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          sonarqube-${{ runner.os }}-
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # adjust version as needed
 
    - name: Install SonarQube Scanner
      run: |
        sudo apt-get install -y unzip
        curl -sSLo /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
        unzip -d /tmp /tmp/sonar-scanner-cli.zip
        sudo mv /tmp/sonar-scanner-4.6.0.2311-linux /opt/sonar-scanner
        sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
 
    - name: SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=github \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=squ_426e58261384efd61d923dfc2a711d2f28314fb3
