name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Adjust Python version as needed

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=github \
            -Dsonar.sources=sonar-scanner.bat -D"sonar.projectKey=github" -D"sonar.sources=D:\talentsprint\custom." -D"sonar.host.url=http://localhost:9099" -D"sonar.token=squ_426e58261384efd61d923dfc2a711d2f28314fb3" -D"sonar.projectBaseDir=D:\talentsprint\custom \
            -Dsonar.host.url=https://localhost:9099 \
            -Dsonar.login=squ_426e58261384efd61d923dfc2a711d2f28314fb3
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
