name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust Python version as needed

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.1.2563-linux.zip
          unzip sonar-scanner-cli-4.7.1.2563-linux.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.7.1.2563-linux/bin"

      - name: Run SonarQube Analysis
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
